export const RENDER_ASIDE = "RENDER_ASIDE";

export const EXPAND_NAVIGATION = "EXPAND_NAVIGATION";
export const COLLAPSE_NAVIGATION = "COLLAPSE_NAVIGATION";

export const LOCK_NAVIGATION = "LOCK_NAVIGATION";
export const UNLOCK_NAVIGATION = "UNLOCK_NAVIGATION";

export const EXPAND_NAVIGATION_REQUEST = "EXPAND_NAVIGATION_REQUEST";
export const COLLAPSE_NAVIGATION_REQUEST = "COLLAPSE_NAVIGATION_REQUEST";
